### ISSUE TITLE
78 vulnerabilities found in dependencies

### ISSUE THREAD

**Issue by loanlaux** [jquense/date-math#12]
When installing `date-arithmetic`, NPM warns that there are 78 known vulnerabilities in the dependencies.

```
$ npm install date-arithmetic
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ date-arithmetic@3.1.0
added 1 package from 1 contributor in 12.883s
[!] 78 vulnerabilities found [4636 packages audited]
    Severity: 66 Low | 6 Moderate | 3 High | 3 Critical
    Run `npm audit` for more detail
```

**Comment by jquense** [comment]
That error isn't for date-math its for your your entire node_modules folder

![image](https://user-images.githubusercontent.com/339286/40556229-ec1eae38-6019-11e8-822c-924067038031.png)

**Comment by loanlaux** [comment]
My bad! Sorry for polluting the issues. I'll be more careful.
