### ISSUE TITLE
subtracting past January goes too far 

### ISSUE THREAD

**Issue by jstacoder** [jquense/date-math#17]
if you substract a month from January you would expect the result to be the prior december, but in fact you get october  from 2 years eariler, 

ie: jan 2019 sub month 

gets oct, 2017

**Comment by xtursky** [comment]
+1 there is some serious problem going on, this makes react-big-calendar month view. which depends upon this, pretty much useless

**Comment by xtursky** [comment]
@jquense thanks for fix. Just planned to write you where is the problem :)
