### ISSUE TITLE
Inconsistencies in unit names

### ISSUE THREAD

**Issue by lo1tuma** [jquense/date-math#2]
Some of the unit names are in its plural form and some in singular:
- plural: `milliseconds`, `seconds`, `minutes,`hours`
- singular: `day`, `week`, `month`, `year`, `decade`, `century`

**Comment by jquense** [comment]
yeah, its an annoying wart, but the reason its that way is consistency with the native `Date` api. i.e. `getMinutes`, `getMonth()`. At this point its not really worth the breaking change, but if it bugs you i'd take a PR that aliases them to a consistent non plural version.

**Comment by lo1tuma** [comment]
Thanks for the explanation, that makes totally sense (not for the inconsistency with the native date api, but for this library). I think I can live with that, adding aliases probably doesn't reduce the confusion.
