### ISSUE TITLE
Getting the library to work on Safari

### ISSUE THREAD

**Issue by IYTEC** [jquense/date-math#21]
I am having issues getting the library to work on Safari. It works well on Chrome, but returns invalid date on Safari. I there any configuration I'm missing or anything I should do?

**Comment by jquense** [comment]
it should work fine on safari, do you have an example?

**Comment by IYTEC** [comment]
Yes @jquense . Let me share that.

`start_date = "2021-04-07 13:24:00" `
`dates.startOf(start_date, 'day')` // 

Returns `Invalid date` on Safari
but returns `Sun Jul 04 2021 00:00:00 GMT+0100 (West Africa Standard Time)` on chrome

**Comment by jquense** [comment]
the API's don't really support using string inputs. It happens to work in this case because it's passed to `new Date()` to clone the input to mutate. You are getting an invalid date because that is not a valid input to `new Date` in Safari i guess. Each browser has different parsing outcomes

**Comment by IYTEC** [comment]
Okay, got it. Thanks for the clarification. I appreciate.
