### ISSUE TITLE
Implement diff function

### ISSUE THREAD

**Issue by lo1tuma** [jquense/date-math#3]
A unit-aware date diff function would very useful.

``` js
dateMath.diff(new Date(2015, 3, 10), new Date(2015, 3, 12), 'day') === 2; // -> true
```

**Comment by jquense** [comment]
Agreed, I try to keep this really light but I've also implemented that function in almost every place i've done any date heavy calculations.

**Comment by crucialfelix** [comment]
You can close this. diff works great. thanks
